export const INICIAR_SESION = "INICIAR_SESION";
export const INICIAR_SESION_CORRECTO = "INICIAR_SESION_CORRECTO";
export const INICIAR_SESION_ERRONEO = "INICIAR_SESION_ERRONEO";

export const PONER_TOKEN = "PONER_TOKEN";
export const QUITAR_TOKEN = "QUITAR_TOKEN";
export const OBTENER_TOKEN = "OBTENER_TOKEN";

export const OBTENER_CLIENTES = "OBTENER_CLIENTES";
export const OBTENER_CLIENTES_CORRECTO = "OBTENER_CLIENTES_CORRECTO";
export const OBTENER_CLIENTES_ERRONEO = "OBTENER_CLIENTES_ERRONEO";

export const OBTENER_ONE_CLIENTE = "OBTENER_ONE_CLIENTE";
export const OBTENER_ONE_CLIENTE_CORRECTO = "OBTENER_ONE_CLIENTE_CORRECTO";
export const OBTENER_ONE_CLIENTE_ERRONEO = "OBTENER_ONE_CLIENTE_ERRONEO";

export const CREATE_CLIENT = "CREATE_CLIENT";
export const CREATE_CLIENT_CORRECTO = "CREATE_CLIENT_CORRECTO";
export const CREATE_CLIENT_ERRONEO = "CREATE_CLIENT_ERRONEO";

export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const UPDATE_CLIENT_CORRECTO = "UPDATE_CLIENT_CORRECTO";
export const UPDATE_CLIENT_ERRONEO = "UPDATE_CLIENT_ERRONEO";
